# Generated by Django 4.1.5 on 2023-02-23 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0002_alter_dibujo_dibujo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dibujo',
            name='dibujo',
            field=models.ImageField(blank=True, null=True, upload_to='static/AppWeb/imagenes'),
        ),
    ]
