# Generated by Django 4.1.5 on 2023-02-23 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0005_dibujo_galeria_alter_dibujo_dibujo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
